parent: ZOneTheme
name: std_joia
display_name: Joia Software Solutions std Child theme
version: 1.0.0
author:
  name: "Joia Software Solutions s.r.l."
  url: "https://www.joiasoftware.it/"

assets:
  use_parent_assets: false
      